Run renovate from docker (#1)
The node version has been failing with error

```
    node_modules/renovate/dist/versioning/index.js:18
        .filter(dirent => dirent.isDirectory() &&
        !dirent.name.startsWith('_'))

    TypeError: dirent.isDirectory is not a function
       at fs_1.default.readdirSync.filter.dirent (/codebuild/output/src091269395/src/node_modules/renovate/dist/versioning/index.js:18:30)
    at Array.filter (<anonymous>)
    at Object.<anonymous> (/codebuild/output/src091269395/src/node_modules/renovate/dist/versioning/index.js:18:6)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/codebuild/output/src091269395/src/node_modules/renovate/dist/config/definitions.js:13:22)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/codebuild/output/src091269395/src/node_modules/renovate/dist/config/index.js:14:34)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
```

Update the cloudformation template to run renovate using docker